"""Initial migration

Revision ID: 4d79422a0f1d
Revises: 8675d80dc77d
Create Date: 2025-01-31 12:26:36.699222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4d79422a0f1d'
down_revision: Union[str, None] = '8675d80dc77d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
