"""Add ram_id column to items table

Revision ID: 5fa45cb53ceb
Revises: c8b5345d2a35
Create Date: 2024-11-02 19:54:55.173947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa45cb53ceb'
down_revision: Union[str, None] = 'c8b5345d2a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('ram_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'RMA', ['ram_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'ram_id')
    # ### end Alembic commands ###
