"""Create users table

Revision ID: 8675d80dc77d
Revises: 02272824d3f2
Create Date: 2025-01-31 10:56:42.496949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8675d80dc77d'
down_revision: Union[str, None] = '02272824d3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('users', 'is_registered')
    op.drop_column('users', 'userphone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userphone', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=15), nullable=True))
    op.add_column('users', sa.Column('is_registered', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=100), nullable=True))
    # ### end Alembic commands ###
