"""Change telegram_id to nullable=True

Revision ID: bf0cbd93c4b1
Revises: 0fb41bb998f6
Create Date: 2024-11-09 14:48:53.290852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bf0cbd93c4b1'
down_revision: Union[str, None] = '0fb41bb998f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
